pipeline{
    
    agent any // we dont have any agents beside the master node

    stages{
        stage("run deployment"){
            steps{
                echo "======== load the Container Image ========"

                dir("devops-exercises-2/06/cicd/cd/ansible") {
                    ansiblePlaybook(
                        playbook: "deploy_random_name_generator.yml",
                        inventory: "inventory/kvm_hosts"
                    )
                }
            }
        }       
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}