pipeline{
    
    agent any // we dont have any agents beside the master node

    stages{
        stage("run deployment"){
            steps{
                echo "======== load the Container Image ========"

                sh """
                ls -la 
                pwd
                """

                ansiblePlaybook(
                    playbook: "ansible/deploy_random_name_generator.yml",
                    inventory: "ansible/inventory/kvm_hosts"
                )

            }
        }       
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}