- name: debug
  hosts: localhost
  tasks:
    - name: get the username running the deploy
      become: false
      local_action: command whoami
      register: username_on_the_host

    - debug: var=username_on_the_host

- name: Deploy the random-name-generator
  hosts: app1
  remote_user: root
  roles:
    - random_name_generator
