---
- name: create to be used by jenkins
  containers.podman.podman_volume:
    state: present
    name: jenkins_server
  become_user: root
  become: yes    

- name: install jenkins 
  containers.podman.podman_container:
    name: jenkins_server
    state: started
    image: docker.io/jenkins/jenkins
    #image: registry.access.redhat.com/openshift3/jenkins-2-rhel7
    ports:
      - "8080:8080"
    volumes:
      - jenkins_server:/var/jenkins_home
  become_user: root
  become: yes

- name: ensure firewall settings
  firewalld:
    port: 8080/tcp
    state: enabled
  become_user: root
  become: yes  

#- name: install jenkins
#  yum:
#    name: jenins
#    state: present
#  become_user: root
#  become: yes

#- name: enable and start jenkins
#  service:
#    name: jenkins
#    enabled: yes
#    state: started  
#  become_user: root
#  become: yes

#- name: ensure firewall settings
#  firewalld:
#    service: http
#    state: enabled
#  become_user: root
#  become: yes    