# load image from jenkins
- name: deliver the Container image
  copy:
    src: /container_images/random_name_generator-latest
    dest: /container_images
  become: yes

# unpack the image
- name: pull the random_name_generator image
  containers.podman.podman_load:
    path: "/container_images/random_name_generator-latest"
      


# deploy the application
