# load image from jenkins
- name: deliver the Container image
  copy:
    src: /container_images/random_name_generator-latest
    dest: /container_images
  become: yes

# unpack the image
#- name: 


# deploy the application
