FROM docker.io/jenkins/jenkins

USER root

RUN echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu focal main" >> /etc/apt/sources.list && \
    apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367 && \
    apt update -y && \
    apt install -y ansible pip pkg-config libvirt-dev podman && \
    pip install libvirt-python pytest

USER jenkins
