pipeline{
    
    agent any // we dont have any agents beside the master node

    stages{
        stage("build Container Image"){
            steps{
                echo "======== Building the Container Image ========"

                sh """
                podman build -t random_name_generator:latest -f Containerfile .
            
                """
            }
        }
        stage("Run Tests"){
            steps{
                echo "======== Test the Application ========"

                sh """
                """
            }
        }
        stage("Store the Image"){
            steps{
                echo "======== Store the Container Image ========"

                sh """
                podman save > random_name_generator.tar localhost/random_name_generator:latest
                mv random_name_generator.tar /image-repository/random_name_generator-latest/random-name-generator.tar
                podman rmi localhost/random_name_generator:latest
                """
            }
        }                
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}