pipeline{
    
    agent any // we dont have any agents beside the master node

    stages{
        stage("build Container Image"){
            steps{
                echo "======== Building the Container Image ========"

                dir("devops-exercises-2/06") {
                    sh """
                    buildah bud --layers -t random_name_generator:latest -f Containerfile.app .
                
                    """
                }
            }
        }
        stage("Run Tests"){
            steps{
                echo "======== Test the Application ========"

                dir("devops-exercises-2/06/app") {
                    sh """
                    pytest
                    """
                }
            }
        }
        stage("Store the Image"){
            steps{
                echo "======== Store the Container Image ========"

                sh """
                buildah push localhost/random_name_generator:latest dir:/container_images/random_name_generator-latest
                """
            }
        }                
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}